#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Pl_Hina_Locomotion_FSM

#include "Basic.hpp"


namespace SDK::Params
{

// Function ABP_Pl_Hina_Locomotion_FSM.ABP_Pl_Hina_Locomotion_FSM_C.ExecuteUbergraph_ABP_Pl_Hina_Locomotion_FSM
// 0x0004 (0x0004 - 0x0000)
struct ABP_Pl_Hina_Locomotion_FSM_C_ExecuteUbergraph_ABP_Pl_Hina_Locomotion_FSM final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_ABP_Pl_Hina_Locomotion_FSM_C_ExecuteUbergraph_ABP_Pl_Hina_Locomotion_FSM;

}

