#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AIBase_AIController

#include "Basic.hpp"

#include "BP_AIBase_AIController_classes.hpp"
#include "BP_AIBase_AIController_parameters.hpp"


namespace SDK
{

// Function BP_AIBase_AIController.BP_AIBase_AIController_C.BPI_AI_Patrol_FindNextPoint
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ATargetPoint**                    TargetPoint                                            (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_AIBase_AIController_C::BPI_AI_Patrol_FindNextPoint(class ATargetPoint** TargetPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIBase_AIController_C", "BPI_AI_Patrol_FindNextPoint");

	Params::BP_AIBase_AIController_C_BPI_AI_Patrol_FindNextPoint Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (TargetPoint != nullptr)
		*TargetPoint = Parms.TargetPoint;
}


// Function BP_AIBase_AIController.BP_AIBase_AIController_C.BPI_AI_Patrol_GetCurrPoints
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class ATargetPoint*>*            Points                                                 (Parm, OutParm)
// int32*                                  LastIndex                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AIBase_AIController_C::BPI_AI_Patrol_GetCurrPoints(TArray<class ATargetPoint*>* Points, int32* LastIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIBase_AIController_C", "BPI_AI_Patrol_GetCurrPoints");

	Params::BP_AIBase_AIController_C_BPI_AI_Patrol_GetCurrPoints Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Points != nullptr)
		*Points = std::move(Parms.Points);

	if (LastIndex != nullptr)
		*LastIndex = Parms.LastIndex;
}


// Function BP_AIBase_AIController.BP_AIBase_AIController_C.BPI_AI_Patrol_GetGroupName
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName*                            GroupName                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AIBase_AIController_C::BPI_AI_Patrol_GetGroupName(class FName* GroupName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIBase_AIController_C", "BPI_AI_Patrol_GetGroupName");

	Params::BP_AIBase_AIController_C_BPI_AI_Patrol_GetGroupName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (GroupName != nullptr)
		*GroupName = Parms.GroupName;
}


// Function BP_AIBase_AIController.BP_AIBase_AIController_C.BPI_AI_Patrol_IsFirstPoint
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ATargetPoint*                     TargetPoint                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AIBase_AIController_C::BPI_AI_Patrol_IsFirstPoint(class ATargetPoint* TargetPoint, bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIBase_AIController_C", "BPI_AI_Patrol_IsFirstPoint");

	Params::BP_AIBase_AIController_C_BPI_AI_Patrol_IsFirstPoint Parms{};

	Parms.TargetPoint = TargetPoint;

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function BP_AIBase_AIController.BP_AIBase_AIController_C.BPI_AI_Patrol_UpdateStatus
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_AIBase_AIController_C::BPI_AI_Patrol_UpdateStatus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIBase_AIController_C", "BPI_AI_Patrol_UpdateStatus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AIBase_AIController.BP_AIBase_AIController_C.ExecuteUbergraph_BP_AIBase_AIController
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AIBase_AIController_C::ExecuteUbergraph_BP_AIBase_AIController(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIBase_AIController_C", "ExecuteUbergraph_BP_AIBase_AIController");

	Params::BP_AIBase_AIController_C_ExecuteUbergraph_BP_AIBase_AIController Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

