#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BackToTitle_State

#include "Basic.hpp"

#include "BP_BackToTitle_State_classes.hpp"
#include "BP_BackToTitle_State_parameters.hpp"


namespace SDK
{

// Function BP_BackToTitle_State.BP_BackToTitle_State_C.ShowClearGameWidget
// (BlueprintCallable, BlueprintEvent)

void UBP_BackToTitle_State_C::ShowClearGameWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BackToTitle_State_C", "ShowClearGameWidget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BackToTitle_State.BP_BackToTitle_State_C.SeamlessTravelToTitle
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_BackToTitle_State_C::SeamlessTravelToTitle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BackToTitle_State_C", "SeamlessTravelToTitle");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BackToTitle_State.BP_BackToTitle_State_C.OnStateBegin
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UBP_BackToTitle_State_C::OnStateBegin()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BackToTitle_State_C", "OnStateBegin");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BackToTitle_State.BP_BackToTitle_State_C.OnSaveClearGameWidgetClosed
// (BlueprintCallable, BlueprintEvent)

void UBP_BackToTitle_State_C::OnSaveClearGameWidgetClosed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BackToTitle_State_C", "OnSaveClearGameWidgetClosed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BackToTitle_State.BP_BackToTitle_State_C.OnClearGameWidgetClose
// (BlueprintCallable, BlueprintEvent)

void UBP_BackToTitle_State_C::OnClearGameWidgetClose()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BackToTitle_State_C", "OnClearGameWidgetClose");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BackToTitle_State.BP_BackToTitle_State_C.ExecuteUbergraph_BP_BackToTitle_State
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_BackToTitle_State_C::ExecuteUbergraph_BP_BackToTitle_State(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BackToTitle_State_C", "ExecuteUbergraph_BP_BackToTitle_State");

	Params::BP_BackToTitle_State_C_ExecuteUbergraph_BP_BackToTitle_State Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BackToTitle_State.BP_BackToTitle_State_C.EnsureSaveCompleteThenShowUI
// (BlueprintCallable, BlueprintEvent)

void UBP_BackToTitle_State_C::EnsureSaveCompleteThenShowUI()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BackToTitle_State_C", "EnsureSaveCompleteThenShowUI");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BackToTitle_State.BP_BackToTitle_State_C.ConstructionScript
// (Event, Protected, BlueprintCallable, BlueprintEvent)

void UBP_BackToTitle_State_C::ConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BackToTitle_State_C", "ConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BackToTitle_State.BP_BackToTitle_State_C.Completed_B6100F594C558A3E2E0DF0AFD0995DF4
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class USaveGame*                        SaveGame                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    bSuccess                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_BackToTitle_State_C::Completed_B6100F594C558A3E2E0DF0AFD0995DF4(class USaveGame* SaveGame, bool bSuccess)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BackToTitle_State_C", "Completed_B6100F594C558A3E2E0DF0AFD0995DF4");

	Params::BP_BackToTitle_State_C_Completed_B6100F594C558A3E2E0DF0AFD0995DF4 Parms{};

	Parms.SaveGame = SaveGame;
	Parms.bSuccess = bSuccess;

	UObject::ProcessEvent(Func, &Parms);
}

}

