#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Condition_Round

#include "Basic.hpp"

#include "BP_Condition_Round_classes.hpp"
#include "BP_Condition_Round_parameters.hpp"


namespace SDK
{

// Function BP_Condition_Round.BP_Condition_Round_C.BP_DoCheckCondition
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UBP_Condition_Round_C::BP_DoCheckCondition()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Condition_Round_C", "BP_DoCheckCondition");

	Params::BP_Condition_Round_C_BP_DoCheckCondition Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

