#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DestroyEnemyByTag

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "SMSystem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DestroyEnemyByTag.BP_DestroyEnemyByTag_C
// 0x0020 (0x0110 - 0x00F0)
class UBP_DestroyEnemyByTag_C final : public USMStateInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FGameplayTag                           DestroyCharacterTag;                               // 0x00F8(0x0008)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash)
	TArray<class AActor*>                         CacheActors;                                       // 0x0100(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, Transient, DisableEditOnInstance, AdvancedDisplay)

public:
	void OnStateBegin();
	void ExecuteUbergraph_BP_DestroyEnemyByTag(int32 EntryPoint);
	void ConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DestroyEnemyByTag_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DestroyEnemyByTag_C")
	}
	static class UBP_DestroyEnemyByTag_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_DestroyEnemyByTag_C>();
	}
};
DUMPER7_ASSERTS_UBP_DestroyEnemyByTag_C;

}

