#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Env_VolumeFogBase

#include "Basic.hpp"

#include "GameNoce_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Env_VolumeFogBase.BP_Env_VolumeFogBase_C
// 0x0000 (0x0358 - 0x0358)
class ABP_Env_VolumeFogBase_C final : public ANoceEnvVolumeFogActor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Env_VolumeFogBase_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Env_VolumeFogBase_C")
	}
	static class ABP_Env_VolumeFogBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Env_VolumeFogBase_C>();
	}
};
DUMPER7_ASSERTS_ABP_Env_VolumeFogBase_C;

}

