#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NoceTutorialInstructor_ClawMaskFocus_Hint

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_NoceTutorialInstructor_ClawMaskFocus_Hint.BP_NoceTutorialInstructor_ClawMaskFocus_Hint_C.IsStartCondition
// 0x0002 (0x0002 - 0x0000)
struct BP_NoceTutorialInstructor_ClawMaskFocus_Hint_C_IsStartCondition final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsStartCondition_ReturnValue;             // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_NoceTutorialInstructor_ClawMaskFocus_Hint_C_IsStartCondition;

}

