#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_OpenDoorByProgress

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameNoce_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_OpenDoorByProgress.BP_OpenDoorByProgress_C
// 0x0010 (0x0140 - 0x0130)
class UBP_OpenDoorByProgress_C final : public UNoceOpenDoorByProgressComp
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0130(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          HasEverUpdated;                                    // 0x0138(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          PreviouslyOpened;                                  // 0x0139(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CachedNeedOpen;                                    // 0x013A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ApplyUpdate();
	void ExecuteUbergraph_BP_OpenDoorByProgress(int32 EntryPoint);
	bool NeedUpdateOpen(bool B);
	void ReceiveBeginPlay();
	void ReceiveTick(float DeltaSeconds);
	void UpdateOpenDoor_BP(bool NeedOpen);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_OpenDoorByProgress_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_OpenDoorByProgress_C")
	}
	static class UBP_OpenDoorByProgress_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_OpenDoorByProgress_C>();
	}
};
DUMPER7_ASSERTS_UBP_OpenDoorByProgress_C;

}

