#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Player_SetAcceptInputActionAndCamera_State

#include "Basic.hpp"

#include "BP_Player_SetAcceptInputActionAndCamera_State_classes.hpp"
#include "BP_Player_SetAcceptInputActionAndCamera_State_parameters.hpp"


namespace SDK
{

// Function BP_Player_SetAcceptInputActionAndCamera_State.BP_Player_SetAcceptInputActionAndCamera_State_C.OnStateBegin
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UBP_Player_SetAcceptInputActionAndCamera_State_C::OnStateBegin()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Player_SetAcceptInputActionAndCamera_State_C", "OnStateBegin");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Player_SetAcceptInputActionAndCamera_State.BP_Player_SetAcceptInputActionAndCamera_State_C.ExecuteUbergraph_BP_Player_SetAcceptInputActionAndCamera_State
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Player_SetAcceptInputActionAndCamera_State_C::ExecuteUbergraph_BP_Player_SetAcceptInputActionAndCamera_State(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Player_SetAcceptInputActionAndCamera_State_C", "ExecuteUbergraph_BP_Player_SetAcceptInputActionAndCamera_State");

	Params::BP_Player_SetAcceptInputActionAndCamera_State_C_ExecuteUbergraph_BP_Player_SetAcceptInputActionAndCamera_State Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Player_SetAcceptInputActionAndCamera_State.BP_Player_SetAcceptInputActionAndCamera_State_C.ConstructionScript
// (Event, Protected, BlueprintCallable, BlueprintEvent)

void UBP_Player_SetAcceptInputActionAndCamera_State_C::ConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Player_SetAcceptInputActionAndCamera_State_C", "ConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Player_SetAcceptInputActionAndCamera_State.BP_Player_SetAcceptInputActionAndCamera_State_C.OnStateUpdate
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Player_SetAcceptInputActionAndCamera_State_C::OnStateUpdate(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Player_SetAcceptInputActionAndCamera_State_C", "OnStateUpdate");

	Params::BP_Player_SetAcceptInputActionAndCamera_State_C_OnStateUpdate Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Player_SetAcceptInputActionAndCamera_State.BP_Player_SetAcceptInputActionAndCamera_State_C.OnStateEnd
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UBP_Player_SetAcceptInputActionAndCamera_State_C::OnStateEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Player_SetAcceptInputActionAndCamera_State_C", "OnStateEnd");

	UObject::ProcessEvent(Func, nullptr);
}

}

