#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SetProgressTag_ByEndingBranch_State

#include "Basic.hpp"

#include "BP_SetProgressTag_ByEndingBranch_State_classes.hpp"
#include "BP_SetProgressTag_ByEndingBranch_State_parameters.hpp"


namespace SDK
{

// Function BP_SetProgressTag_ByEndingBranch_State.BP_SetProgressTag_ByEndingBranch_State_C.SetSpecifyProgressTag
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              InProgressTag                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UBP_SetProgressTag_ByEndingBranch_State_C::SetSpecifyProgressTag(const struct FGameplayTag& InProgressTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SetProgressTag_ByEndingBranch_State_C", "SetSpecifyProgressTag");

	Params::BP_SetProgressTag_ByEndingBranch_State_C_SetSpecifyProgressTag Parms{};

	Parms.InProgressTag = std::move(InProgressTag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SetProgressTag_ByEndingBranch_State.BP_SetProgressTag_ByEndingBranch_State_C.OnStateBegin
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UBP_SetProgressTag_ByEndingBranch_State_C::OnStateBegin()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SetProgressTag_ByEndingBranch_State_C", "OnStateBegin");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SetProgressTag_ByEndingBranch_State.BP_SetProgressTag_ByEndingBranch_State_C.ExecuteUbergraph_BP_SetProgressTag_ByEndingBranch_State
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_SetProgressTag_ByEndingBranch_State_C::ExecuteUbergraph_BP_SetProgressTag_ByEndingBranch_State(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SetProgressTag_ByEndingBranch_State_C", "ExecuteUbergraph_BP_SetProgressTag_ByEndingBranch_State");

	Params::BP_SetProgressTag_ByEndingBranch_State_C_ExecuteUbergraph_BP_SetProgressTag_ByEndingBranch_State Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SetProgressTag_ByEndingBranch_State.BP_SetProgressTag_ByEndingBranch_State_C.ConstructionScript
// (Event, Protected, BlueprintCallable, BlueprintEvent)

void UBP_SetProgressTag_ByEndingBranch_State_C::ConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SetProgressTag_ByEndingBranch_State_C", "ConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

