#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ShowCredit_State

#include "Basic.hpp"

#include "BP_ShowCredit_State_classes.hpp"
#include "BP_ShowCredit_State_parameters.hpp"


namespace SDK
{

// Function BP_ShowCredit_State.BP_ShowCredit_State_C.OnStateEnd
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UBP_ShowCredit_State_C::OnStateEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ShowCredit_State_C", "OnStateEnd");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ShowCredit_State.BP_ShowCredit_State_C.OnStateBegin
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UBP_ShowCredit_State_C::OnStateBegin()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ShowCredit_State_C", "OnStateBegin");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ShowCredit_State.BP_ShowCredit_State_C.ExecuteUbergraph_BP_ShowCredit_State
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ShowCredit_State_C::ExecuteUbergraph_BP_ShowCredit_State(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ShowCredit_State_C", "ExecuteUbergraph_BP_ShowCredit_State");

	Params::BP_ShowCredit_State_C_ExecuteUbergraph_BP_ShowCredit_State Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ShowCredit_State.BP_ShowCredit_State_C.ConstructionScript
// (Event, Protected, BlueprintCallable, BlueprintEvent)

void UBP_ShowCredit_State_C::ConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ShowCredit_State_C", "ConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ShowCredit_State.BP_ShowCredit_State_C.OnWidgetClosed
// (BlueprintCallable, BlueprintEvent)

void UBP_ShowCredit_State_C::OnWidgetClosed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ShowCredit_State_C", "OnWidgetClosed");

	UObject::ProcessEvent(Func, nullptr);
}

}

