#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TemporaryGameSave_State

#include "Basic.hpp"

#include "BP_TemporaryGameSave_State_classes.hpp"
#include "BP_TemporaryGameSave_State_parameters.hpp"


namespace SDK
{

// Function BP_TemporaryGameSave_State.BP_TemporaryGameSave_State_C.ShowAutoSaveIcon
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Show                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_TemporaryGameSave_State_C::ShowAutoSaveIcon(bool Show)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TemporaryGameSave_State_C", "ShowAutoSaveIcon");

	Params::BP_TemporaryGameSave_State_C_ShowAutoSaveIcon Parms{};

	Parms.Show = Show;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TemporaryGameSave_State.BP_TemporaryGameSave_State_C.OnStateUpdate
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_TemporaryGameSave_State_C::OnStateUpdate(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TemporaryGameSave_State_C", "OnStateUpdate");

	Params::BP_TemporaryGameSave_State_C_OnStateUpdate Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TemporaryGameSave_State.BP_TemporaryGameSave_State_C.OnStateBegin
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UBP_TemporaryGameSave_State_C::OnStateBegin()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TemporaryGameSave_State_C", "OnStateBegin");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TemporaryGameSave_State.BP_TemporaryGameSave_State_C.GetTeleportActor
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// TSoftObjectPtr<class AActor>*           TeleportActor                                          (Parm, OutParm, HasGetValueTypeHash)

void UBP_TemporaryGameSave_State_C::GetTeleportActor(TSoftObjectPtr<class AActor>* TeleportActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TemporaryGameSave_State_C", "GetTeleportActor");

	Params::BP_TemporaryGameSave_State_C_GetTeleportActor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (TeleportActor != nullptr)
		*TeleportActor = Parms.TeleportActor;
}


// Function BP_TemporaryGameSave_State.BP_TemporaryGameSave_State_C.ExecuteUbergraph_BP_TemporaryGameSave_State
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_TemporaryGameSave_State_C::ExecuteUbergraph_BP_TemporaryGameSave_State(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TemporaryGameSave_State_C", "ExecuteUbergraph_BP_TemporaryGameSave_State");

	Params::BP_TemporaryGameSave_State_C_ExecuteUbergraph_BP_TemporaryGameSave_State Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TemporaryGameSave_State.BP_TemporaryGameSave_State_C.ConstructionScript
// (Event, Protected, BlueprintCallable, BlueprintEvent)

void UBP_TemporaryGameSave_State_C::ConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TemporaryGameSave_State_C", "ConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

