#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_EnemyInSight

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_EnemyInSight.GE_EnemyInSight_C
// 0x0000 (0x0A70 - 0x0A70)
class UGE_EnemyInSight_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_EnemyInSight_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_EnemyInSight_C")
	}
	static class UGE_EnemyInSight_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_EnemyInSight_C>();
	}
};
DUMPER7_ASSERTS_UGE_EnemyInSight_C;

}

