#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_FillCurrentMaxSanityToMinValue

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_FillCurrentMaxSanityToMinValue.GE_FillCurrentMaxSanityToMinValue_C
// 0x0000 (0x0A70 - 0x0A70)
class UGE_FillCurrentMaxSanityToMinValue_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_FillCurrentMaxSanityToMinValue_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_FillCurrentMaxSanityToMinValue_C")
	}
	static class UGE_FillCurrentMaxSanityToMinValue_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_FillCurrentMaxSanityToMinValue_C>();
	}
};
DUMPER7_ASSERTS_UGE_FillCurrentMaxSanityToMinValue_C;

}

