#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_Pl_DodgedRecently

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Pl_DodgedRecently.GE_Pl_DodgedRecently_C
// 0x0000 (0x0A70 - 0x0A70)
class UGE_Pl_DodgedRecently_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_Pl_DodgedRecently_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_Pl_DodgedRecently_C")
	}
	static class UGE_Pl_DodgedRecently_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Pl_DodgedRecently_C>();
	}
};
DUMPER7_ASSERTS_UGE_Pl_DodgedRecently_C;

}

