#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TitleFlow_ChooserArrow

#include "Basic.hpp"

#include "GameNoce_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_TitleFlow_ChooserArrow.WBP_TitleFlow_ChooserArrow_C
// 0x0008 (0x0390 - 0x0388)
class UWBP_TitleFlow_ChooserArrow_C final : public UNoceChooserArrowWidget
{
public:
	class UNoceHitArea*                           NoceHitArea_132;                                   // 0x0388(0x0008)(ExportObject, ZeroConstructor, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_TitleFlow_ChooserArrow_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_TitleFlow_ChooserArrow_C")
	}
	static class UWBP_TitleFlow_ChooserArrow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_TitleFlow_ChooserArrow_C>();
	}
};
DUMPER7_ASSERTS_UWBP_TitleFlow_ChooserArrow_C;

}

