#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Letter_TabItem

#include "Basic.hpp"

#include "GameNoce_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Letter_TabItem.WBP_Letter_TabItem_C
// 0x0000 (0x0380 - 0x0380)
class UWBP_Letter_TabItem_C final : public UNoceLetterTabItemWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Letter_TabItem_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Letter_TabItem_C")
	}
	static class UWBP_Letter_TabItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Letter_TabItem_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Letter_TabItem_C;

}

