#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SanityFlowerBall

#include "Basic.hpp"

#include "GameNoce_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_SanityFlowerBall.WBP_SanityFlowerBall_C
// 0x0000 (0x03B0 - 0x03B0)
class UWBP_SanityFlowerBall_C final : public UNoceMaterialSanityFlowerWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_SanityFlowerBall_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_SanityFlowerBall_C")
	}
	static class UWBP_SanityFlowerBall_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_SanityFlowerBall_C>();
	}
};
DUMPER7_ASSERTS_UWBP_SanityFlowerBall_C;

}

