name: Build SHFMod DLL

on:
  push:
    tags:
      - 'v*'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: msbuild SHFMod.sln /p:Configuration=Release /p:Platform=x64

    - name: Package Release Files
      run: Compress-Archive -Path x64/Release/SHFMod.* -DestinationPath SHFMod-${{ github.ref_name }}.zip
      shell: powershell
      
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: SHFMod-${{ github.ref_name }}.zip
