name: Build SHFMod DLL

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: msbuild SHFMod.sln /p:Configuration=Release /p:Platform=x64

    - name: Upload DLL Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SHFMod-Release-DLL
        path: x64/Release/SHFMod.dll
